import { Routes } from 'nest-router'
import { CategoriasModule } from './categorias/categorias.module'
import { DetalleVentasModule } from './detalle-ventas/detalle-ventas.module'
import { DireccionesModule } from './direcciones/direcciones.module'
import { ImagenesModule } from './imagenes/imagenes.module'
import { MesasModule } from './mesas/mesas.module'
import { MetodosPagoModule } from './metodos-pago/metodos-pago.module'
import { ProductosModule } from './productos/productos.module'
import { ReservasModule } from './reservas/reservas.module'
import { ReservasMesasModule } from './reservas-mesas/reservas-mesas.module'
import { RestaurantesModule } from './restaurantes/restaurantes.module'
import { RestaurantesMetodosPagoModule } from './restaurantes-metodos-pago/restaurantes-metodos-pago.module'
import { RolesModule } from './roles/roles.module'
import { TercerosModule } from './terceros/terceros.module'
import { UsuariosModule } from './usuarios/usuarios.module'
import { VentasModule } from './ventas/ventas.module'

export const publicRoutes: Routes = [
  { path: 'categorias', module: CategoriasModule },
  { path: 'detalle-ventas', module: DetalleVentasModule },
  { path: 'direcciones', module: DireccionesModule },
  { path: 'imagenes', module: ImagenesModule },
  { path: 'mesas', module: MesasModule },
  { path: 'metodos-pago', module: MetodosPagoModule },
  { path: 'productos', module: ProductosModule },
  { path: 'reservas', module: ReservasModule },
  { path: 'reservas-mesas', module: ReservasMesasModule },
  { path: 'restaurantes', module: RestaurantesModule },
  { path: 'restaurantes-metodos-pago', module: RestaurantesMetodosPagoModule },
  { path: 'roles', module: RolesModule },
  { path: 'terceros', module: TercerosModule },
  { path: 'usuarios', module: UsuariosModule },
  { path: 'ventas', module: VentasModule }
]
